# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        article:
            quality: 95
            filters:
                thumbnail:
                    size: [500]
                    mode: outbound
                    allow_upscale: true

        article_thumbnail:
            quality: 65
            filters:
                thumbnail:
                    size: [200, 250]
                    mode: outbound
                    allow_upscale: true

        article_form:
            quality: 75
            filters:
                thumbnail:
                    size:       [400]
                    mode:       outbound
                    allow_upscale: true

    resolvers:
        default:
            web_path:
                cache_prefix: media/cache